version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cloudlicense
      POSTGRES_USER: clouduser
      POSTGRES_PASSWORD: cloudpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clouduser -d cloudlicense"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: clouduser
      DB_PASSWORD: cloudpass
      DB_NAME: cloudlicense
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASS: ""
      NOTIFY_EMAIL: test@example.com
      # Add other env vars as needed (JWT, etc)
    ports:
      - "8080:8080"
    command: ["./server"]

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP

volumes:
  db_data:
